// lib/features/payslip/payslip_pdf_helper.dart
import 'dart:typed_data';
import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

Future<Uint8List> generatePayslipPdf({
  required Map<String, dynamic> staff,
  required Map<String, dynamic> payslip,
}) async {
  final pdf = pw.Document();

  // ========= LOAD LOGO =========
  final smartbayuLogo = pw.MemoryImage(
    (await rootBundle.load('assets/logos/smartbayu_logo.png'))
        .buffer
        .asUint8List(),
  );

  final bayuLogo = pw.MemoryImage(
    (await rootBundle.load('assets/logos/bayu_lestari_logo.png'))
        .buffer
        .asUint8List(),
  );

  // ========= STAFF INFO FROM users/{uid} =========
  final staffName = (staff['displayName'] ??
      staff['name'] ??
      staff['staffName'] ??
      staff['email'] ??
      '-')
      .toString();
  final employeeId = (staff['employeeId'] ?? '-').toString();
  final department = (staff['department'] ?? '-').toString();
  final employmentType = (staff['employmentType'] ?? '-').toString();
  final email = (staff['email'] ?? '-').toString();
  final joinDate = (staff['joinDate'] ?? '-').toString();
  final siteName = (staff['siteName'] ?? staff['site'] ?? '').toString();

  // ========= PAYSLIP INFO FROM users/{uid}/payslips/{doc} =========
  final periodLabel = (payslip['monthLabel'] ?? '-').toString();
  final basicSalary = _toDouble(payslip['basicSalary']);
  final allowance = _toDouble(payslip['allowance']);
  final overtime = _toDouble(payslip['overtime']);
  final deductions = _toDouble(payslip['deductions']);
  final kwsp = _toDouble(payslip['kwsp']);
  final socso = _toDouble(payslip['socso']);
  final netPay = _toDouble(payslip['netPay']);

  pdf.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(24),
      build: (context) => [
        // ========= HEADER (LOGO KIRI & KANAN) =========
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.center,
          children: [
            pw.Container(
              width: 70,
              height: 70,
              child: pw.Image(smartbayuLogo),
            ),
            pw.Column(
              mainAxisSize: pw.MainAxisSize.min,
              children: [
                pw.Text(
                  'PAYSLIP',
                  style: pw.TextStyle(
                    fontSize: 20,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Bayu Lestari Resort',
                  style: const pw.TextStyle(fontSize: 12),
                ),
                pw.Text(
                  'Generated by SmartBayu HR System',
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ],
            ),
            pw.Container(
              width: 70,
              height: 70,
              child: pw.Image(bayuLogo),
            ),
          ],
        ),

        pw.SizedBox(height: 16),
        pw.Divider(),

        // ========= EMPLOYEE + PAYSLIP DETAILS =========
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // LEFT: Employee info
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'Employee Information',
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Text('Name          : $staffName'),
                pw.Text('Employee ID   : $employeeId'),
                pw.Text('Department    : $department'),
                pw.Text('Employment    : $employmentType'),
                if (siteName.isNotEmpty) pw.Text('Site          : $siteName'),
                pw.Text('Email         : $email'),
                pw.Text('Join Date     : $joinDate'),
              ],
            ),

            // RIGHT: Payslip info
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'Payslip Details',
                  style: pw.TextStyle(
                    fontSize: 12,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 6),
                pw.Text('Period : $periodLabel'),
                pw.Text('Prepared via SmartBayu'),
              ],
            ),
          ],
        ),

        pw.SizedBox(height: 20),

        // ========= TABLE EARNINGS vs DEDUCTIONS =========
        pw.Table(
          border: pw.TableBorder.all(color: PdfColors.grey),
          columnWidths: {
            0: const pw.FlexColumnWidth(2),
            1: const pw.FlexColumnWidth(1),
            2: const pw.FlexColumnWidth(2),
            3: const pw.FlexColumnWidth(1),
          },
          children: [
            pw.TableRow(
              decoration: const pw.BoxDecoration(color: PdfColors.grey300),
              children: [
                _headerCell('Earnings'),
                _headerCell('Amount (RM)'),
                _headerCell('Deductions'),
                _headerCell('Amount (RM)'),
              ],
            ),
            pw.TableRow(
              children: [
                _cell('Basic Salary'),
                _cell(basicSalary.toStringAsFixed(2)),
                _cell('KWSP'),
                _cell(kwsp.toStringAsFixed(2)),
              ],
            ),
            pw.TableRow(
              children: [
                _cell('Allowance'),
                _cell(allowance.toStringAsFixed(2)),
                _cell('SOCSO'),
                _cell(socso.toStringAsFixed(2)),
              ],
            ),
            pw.TableRow(
              children: [
                _cell('Overtime'),
                _cell(overtime.toStringAsFixed(2)),
                _cell('Other Deductions'),
                _cell(deductions.toStringAsFixed(2)),
              ],
            ),
          ],
        ),

        pw.SizedBox(height: 16),

        // ========= NET PAY =========
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Net Pay (RM):',
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.Text(
              netPay.toStringAsFixed(2),
              style: pw.TextStyle(
                fontSize: 14,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ],
        ),

        pw.SizedBox(height: 30),

        // ========= SIGNATURE =========
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              children: [
                pw.Text('________________________'),
                pw.Text(
                  'Employee Signature',
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ],
            ),
            pw.Column(
              children: [
                pw.Text('________________________'),
                pw.Text(
                  'Authorized Signatory',
                  style: const pw.TextStyle(fontSize: 10),
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );

  return pdf.save();
}

// Helpers
double _toDouble(dynamic v) {
  if (v == null) return 0;
  if (v is num) return v.toDouble();
  return double.tryParse(v.toString()) ?? 0;
}

pw.Widget _headerCell(String text) {
  return pw.Padding(
    padding: const pw.EdgeInsets.all(6),
    child: pw.Text(
      text,
      style: pw.TextStyle(
        fontSize: 11,
        fontWeight: pw.FontWeight.bold,
      ),
    ),
  );
}

pw.Widget _cell(String text) {
  return pw.Padding(
    padding: const pw.EdgeInsets.all(6),
    child: pw.Text(
      text,
      style: const pw.TextStyle(fontSize: 10),
    ),
  );
}
